name: Deploy docs to AWS S3

# on:
#   push:
#     branches:
#       - develop
#       - stage
#       - main

# Configure Manual Trigger
on:
  workflow_dispatch:
    secrets: inherit
    inputs:
      environment:
        description: 'Which environment to deploy to'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - stage
          - main

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get install -y --no-install-recommends doxygen

    - name: Generate Doxygen documentation
      run: doxygen Doxyfile

    - name: Use variables
      run: |
        echo "AWS_REGION: ${{ vars.AWS_REGION }}"
        echo "AWS_REGION no vars context: $AWS_REGION"
        echo "AWS_REGION env context: ${{ env.AWS_REGION }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        audience: sts.amazonaws.com
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

    - name: Sync S3 bucket
      run: |
        aws s3 sync ./documentation/html s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
